name: Build webMAN Custom Rebug

on:
  workflow_dispatch:
  push:
    paths:
      - 'flags.h'

jobs:
  compile:
    runs-on: ubuntu-latest
    # MENGGUNAKAN CONTAINER DARI GHCR (GITHUB CONTAINER REGISTRY)
    container: ghcr.io/ps3dev/ps3dev:latest 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile
        run: |
          make clean
          make all

      - name: Upload Hasil Build
        uses: actions/upload-artifact@v4
        with:
          name: webMAN-Cobra81-Rebug-Optimized
          path: |
            *.pkg
            *.sprx
