name: Build webMAN Custom Rebug

on:
  workflow_dispatch:
  push:
    paths:
      - 'flags.h'

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          # Menambahkan libelf-dev yang diperlukan oleh ps3toolchain
          sudo apt-get install -y build-essential autoconf automake bison flex texinfo libgmp-dev libmpfr-dev libmpc-dev libssl-dev libcurl4-openssl-dev zlib1g-dev libreadline-dev libelf-dev libtool

      - name: Build PS3 Toolchain
        run: |
          git clone https://github.com/ps3dev/ps3toolchain.git
          cd ps3toolchain
          ./toolchain.sh
          
      - name: Setup Environment Variables
        run: |
          echo "/usr/local/ps3dev/bin" >> $GITHUB_PATH
          echo "/usr/local/ps3dev/ppu/bin" >> $GITHUB_PATH
          echo "PS3DEV=/usr/local/ps3dev" >> $GITHUB_ENV
          echo "PSL1GHT=/usr/local/ps3dev" >> $GITHUB_ENV

      - name: Compile webMAN-MOD
        run: |
          make clean
          make all

      - name: Upload Hasil Build
        uses: actions/upload-artifact@v4
        with:
          name: webMAN-Cobra81-Rebug-Optimized
          path: |
            *.pkg
            *.sprx
